name: 'AutoUpdate'
 
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: 'Run autoupdate.sh'
      run: bash .github/workflows/autoupdate.sh
    - name: Commit and push files
      run: |
        gh auth setup-git
        git config --local user.email "github-actions@noreply.github.com"
        git config --local user.name "github-actions"
        git add .
        git commit -m "Update `date`" -a
        git push origin master
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_HOST: "github.com"


